### ISSUE TITLE
Refactor Components with hooks

### ISSUE THREAD

**Issue by Odongo006** [Odongo006/math-magician-app#4]
Project name: Math Magicians - refactor with hooks❗️❗️

Project description: In this project the Calculator component that was developed in the past projects will be refactored. Instead of using class based components, now hooks will be used.

Project requirements:
Refactor the Calculator component (components/Calculator.js) from a class based component to a functional component with hooks.
After the refactor is done, test the app in the browser. It should keep the same functionality.
❗❗️❗️❗️❗️❗️ IMPORTANT NOTE: If you already use functional components, you can create a GitHub issue in which you describe how you use functional components and ask for a code review based on your issue.

Note: The project was at first developed using class based component. But it was refactored to a functional component based on code reviewer's feedback.

**Comment by AnselemOdims** [comment]
### Hi @Odongo006 , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Even though the `Calculator` component uses a functional component, you are expected to describe how you use functional components. Please kindly describe how to use functional components

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Odongo006** [comment]
Hello @AnselemOdims  Thank you for your feedback. I apologize for not providing enough details on how functional components are used in the code. In this project, a functional component is used by defining a function called Calculator() that returns the JSX elements that define the calculator UI. The useState hook is used to define a state object called state and a function called setState that can be used to update the state. The handleInput function is defined using an arrow function expression, and it calls the setState function with the result of calling the calculate function with the current state and the text content of the clicked button. Finally, the Calculator function is exported as the default export of the module using the export default statement at the end of the file. I hope this clarifies how functional components are used in my code. Please let me know if you have any further suggestions or feedback

**Comment by rotimiazeez** [comment]
Hi @Odongo006 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlight
### Good job explaining how functional components works

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
